### ISSUE TITLE
I can't seem to change the font size.

### ISSUE THREAD

**Issue by fwanky** [jonniek/mpv-playlistmanager#14]
I tried editing size:10 to size:3 but it didn't change.

**Comment by jonniek** [comment]
Did you edit the lua file?

You need to edit `style_ass_tags = "",` to be `style_ass_tags = "{\\fs3}",`

**Comment by fwanky** [comment]
Nope, that didn't work :( I Must be doing something wrong, I want it like you have it in the previews, it's MASSIVE for me 

https://i.imgur.com/LBufbK4.jpg

**Comment by jonniek** [comment]
That's odd. Do you have a script-opt file for playlistmanager? In case you have then you need to edit the value in there since it will override the lua config.

Like so `style_ass_tags={\fs3}`, you can also try adjusting `scale_playlist_by_window=yes` to no if it helps with size.

**Comment by fwanky** [comment]
Changed scale_playlist_by_window=yes, to no as you said.

https://0x0.st/zo0u.png it's still WAY TOO big. Would you like me to upload my configs?

**Comment by jonniek** [comment]
I see. Yes, I could try to reproduce this with your configs.

As a sanity check can you confirm that changing some other of the settings makes a change in behavior. For example edit the `playlist_header` setting to have some random string in it. After restarting this string should be visible when you open the playlist.

**Comment by fwanky** [comment]
LUA;
https://ghostbin.com/paste/5am3e
.conf 
https://ghostbin.com/paste/6mjeq

**Comment by fwanky** [comment]
From whatI can see and what i've added it should work,  just well. Fine? but it's being odd.

**Comment by jonniek** [comment]
You need to either delete your conf file or then edit conf file line 64 to `style_ass_tags={\fs3}`. The conf file will override the settings in lua file so any changes ton the lua file will have no effect in the presence of a conf file.

**Comment by fwanky** [comment]
Thanks, lmfao. My bad there.
