### ISSUE TITLE
No Duplicates

### ISSUE THREAD

**Issue by Cananbolt** [jonniek/mpv-playlistmanager#72]
When pressing the keybind to load files, is there a way for the script not to load files that were already in the playlist? Hence, no duplicates.

**Comment by jonniek** [comment]
Quick fix in bc139f779080469840c55504acbbf36a7c9e6427

It's naive and only looks at filenames for duplicates. Duplicate filenames between directories is not handled, because I'm not sure how that would be done correctly.

**Comment by Cananbolt** [comment]
I went ahead and tried it out, and this is exactly what I wanted. Thank you so much.
